DROP TABLE IF EXISTS customer;

CREATE TABLE customer (
  CUSTOMER_ID INT AUTO_INCREMENT  PRIMARY KEY,
  CUSTOMERNAME VARCHAR(250) NOT NULL,
  CUSTOMERCONTACTNUMBER VARCHAR(250) NOT NULL,
  CUSTOMERADDRESS VARCHAR(250) DEFAULT NULL,
  USERNAME VARCHAR(250) DEFAULT NULL,
  PASSWORD VARCHAR(250) DEFAULT NULL
);

INSERT INTO customer (customerName, customerContactNumber, customerAddress,USERNAME,PASSWORD) VALUES
  ('Prasanth', '8765', 'Peringara','Prasanth1','1234'),
  ('Sidhu', '1234', 'Thiruvalla','Sidhu303','5678');